import {
    EnemyType,
    EnemyBulletType,
    EnemyEntity,
} from '@/types';

// ==================== 敌人配置 ====================
export const EnemyConfig: Record<EnemyType, EnemyEntity> = {
    [EnemyType.NORMAL]: {
        type: EnemyType.NORMAL,
        id: 'enemy_normal',
        name: 'Scout',
        chineseName: '侦察机',
        describe: '敌军基础侦察单位,轻装甲低速度,是战场上最常见的炮灰,也是积累分数的主要来源。',
        color: '#ff4444',
        baseHp: 30,
        hpPerLevel: 10,
        baseSpeed: 2,
        speedPerLevel: 0.5,
        sprite: 'enemy_normal',
        size: { width: 40, height: 40 },
        score: 100,
        weapon: { bulletType: EnemyBulletType.ORB, frequency: 0.015 }
    },
    [EnemyType.FAST]: {
        type: EnemyType.FAST,
        id: 'enemy_fast',
        name: 'Wing',
        chineseName: '疾风飞翼',
        describe: '高速飞翼战机,以折线轨迹高速机动难以锁定,虽然装甲薄弱但射速惊人,是灵活而危险的对手。',
        color: '#aa44ff',
        baseHp: 10,
        hpPerLevel: 2,
        baseSpeed: 10,
        speedPerLevel: 0.5,
        sprite: 'enemy_fast',
        size: { width: 30, height: 40 },
        score: 200,
        weapon: { bulletType: EnemyBulletType.ORB, frequency: 0.05 }
    },
    [EnemyType.TANK]: {
        type: EnemyType.TANK,
        id: 'enemy_tank',
        name: 'Tank',
        chineseName: '重装坦克',
        describe: '搭载纳米复合装甲的移动堡垒,吸收80%常规武器伤害,虽然移动缓慢但配备矢量推进系统可短距冲刺,需要集火才能快速摧毁。',
        color: '#44ff44',
        baseHp: 60,
        hpPerLevel: 20,
        baseSpeed: 1,
        speedPerLevel: 0,
        sprite: 'enemy_tank',
        size: { width: 60, height: 60 },
        score: 300,
        weapon: { bulletType: EnemyBulletType.ORB, frequency: 0.015 }
    },
    [EnemyType.KAMIKAZE]: {
        type: EnemyType.KAMIKAZE,
        id: 'enemy_kamikaze',
        name: 'Kamikaze',
        chineseName: '自杀尖刺',
        describe: '装备量子斥力场的高速突击单位,接近时瞬间加速至亚光速,机身覆盖超硬合金刺状结构,血量极低但速度极快,以冲撞造成致命伤害。',
        color: '#ffaa44',
        baseHp: 5,
        hpPerLevel: 1,
        baseSpeed: 10,
        speedPerLevel: 0.8,
        sprite: 'enemy_kamikaze',
        size: { width: 30, height: 30 },
        score: 400,
        weapon: { bulletType: EnemyBulletType.ORB, frequency: 0.02 }
    },
    [EnemyType.ELITE_GUNBOAT]: {
        type: EnemyType.ELITE_GUNBOAT,
        id: 'enemy_gunboat',
        name: 'Gunboat',
        chineseName: '精英炮艇',
        describe: '星核驱动的精英级重型炮艇,血量火力机动性全面超越常规单位,同时锁定多目标发射能量聚合光束,核心反应堆护盾抵御90%常规攻击,是敌方舰队的终极杀器。',
        color: '#4444ff',
        baseHp: 100,
        hpPerLevel: 10,
        baseSpeed: 0.5,
        speedPerLevel: 0,
        sprite: 'enemy_gunboat',
        size: { width: 70, height: 50 },
        score: 500,
        weapon: { bulletType: EnemyBulletType.RAPID, frequency: 0.02, speed: 4 },
    },
    [EnemyType.LASER_INTERCEPTOR]: {
        type: EnemyType.LASER_INTERCEPTOR,
        id: 'enemy_interceptor',
        name: 'Interceptor',
        chineseName: '光束拦截机',
        describe: '装备相位锁定光束炮的双翼拦截机,在战场中段悬停蓄力后发射切割空间的强大激光束,对直线上所有目标造成毁灭性打击。',
        color: '#44ffff',
        baseHp: 80,
        hpPerLevel: 15,
        baseSpeed: 4,
        speedPerLevel: 0,
        sprite: 'enemy_interceptor',
        size: { width: 50, height: 50 },
        score: 600,
        weapon: { bulletType: EnemyBulletType.BEAM, speed: 12, damage: 30, chargeTime: 2000, cooldownTime: 1000 }
    },
    [EnemyType.MINE_LAYER]: {
        type: EnemyType.MINE_LAYER,
        id: 'enemy_layer',
        name: 'Mine Layer',
        chineseName: '战术布雷机',
        describe: '配备量子感应地雷部署系统的战术单位,缓慢移动但持续留下隐形空雷,根据能量特征自动触发,形成致命的防御网络。',
        color: '#aaaa44',
        baseHp: 60,
        hpPerLevel: 10,
        baseSpeed: 1.5,
        speedPerLevel: 0,
        sprite: 'enemy_layer',
        size: { width: 60, height: 40 },
        score: 700,
        weapon: { bulletType: EnemyBulletType.HEAVY, interval: 1500, damage: 25 },
    },
    [EnemyType.PULSAR]: {
        type: EnemyType.PULSAR,
        id: 'enemy_pulsar',
        name: 'Pulsar',
        chineseName: '脉冲战机',
        describe: '轻量化合金机身的高速战机,配备高频脉冲武器系统在短时间内倾泻大量弹药,虽然装甲薄弱但依靠高机动性规避火力。',
        color: '#ff44ff',
        baseHp: 15,
        hpPerLevel: 5,
        baseSpeed: 6,
        speedPerLevel: 0.5,
        sprite: 'enemy_pulsar',
        size: { width: 32, height: 32 },
        score: 250,
        weapon: { bulletType: EnemyBulletType.RAPID, frequency: 0.08, speed: 6 },
    },
    [EnemyType.FORTRESS]: {
        type: EnemyType.FORTRESS,
        id: 'enemy_fortress',
        name: 'Fortress',
        chineseName: '空中堡垒',
        describe: '搭载多层能量护盾和复合装甲的重装单位,移动缓慢但火力巨大,多管火炮系统覆盖广阔战场,是敌方舰队的核心火力输出。',
        color: '#666666',
        baseHp: 200,
        hpPerLevel: 10,
        baseSpeed: 0.8,
        speedPerLevel: 0,
        sprite: 'enemy_fortress',
        size: { width: 70, height: 70 },
        score: 800,
        weapon: { bulletType: EnemyBulletType.ORB, frequency: 0.02 }
    },
    [EnemyType.STALKER]: {
        type: EnemyType.STALKER,
        id: 'enemy_stalker',
        name: 'Stalker',
        chineseName: '猎杀追踪机',
        describe: '装备量子纠缠锁定系统的精英猎杀单位,动作灵活爆发伤害高,预判移动轨迹发射的追踪弹几乎无法被常规手段规避。',
        color: '#ff8844',
        baseHp: 30,
        hpPerLevel: 10,
        baseSpeed: 5,
        speedPerLevel: 0.5,
        sprite: 'enemy_stalker',
        size: { width: 36, height: 36 },
        score: 350,
        weapon: { bulletType: EnemyBulletType.HOMING, frequency: 0.03, speed: 3 },
    },
    [EnemyType.BARRAGE]: {
        type: EnemyType.BARRAGE,
        id: 'enemy_barrage',
        name: 'Barrage',
        chineseName: '弹幕压制机',
        describe: '搭载多管螺旋弹幕系统的战术压制单位,制造覆盖面极广的弹幕,螺旋能量弹形成复杂弹道网络,迫使玩家在极小安全区域内机动。',
        color: '#8844ff',
        baseHp: 100,
        hpPerLevel: 10,
        baseSpeed: 1.2,
        speedPerLevel: 0.1,
        sprite: 'enemy_barrage',
        size: { width: 50, height: 50 },
        score: 600,
        weapon: { bulletType: EnemyBulletType.SPIRAL, frequency: 0.1, speed: 3 },
    }
};