import {
    BossWeaponType,
    BossWeaponEntity,
} from '@/types';

// ==================== Boss武器配置 ====================
export const BossWeaponConfig: Record<BossWeaponType, BossWeaponEntity> = {
    [BossWeaponType.RADIAL]: {
        type: BossWeaponType.RADIAL,
        id: 'boss_weapon_radial',
        name: 'Radial',
        chineseName: '全向弹幕',
        describe: '量子脉冲加速引擎驱动的环形弹幕系统，超光速同时发射多枚高能弹丸，形成360度无死角的致命弹幕网，覆盖范围广密度极高，是Boss的基础范围攻击手段。',
        bulletSpeed: 3.0,
        bulletCount: 8,
        fireRate: 0.05,
        cooldown: 0,
        color: '#ff4444',
        maxLevel: 9,
    },
    [BossWeaponType.TARGETED]: {
        type: BossWeaponType.TARGETED,
        id: 'boss_weapon_targeted',
        name: 'Targeted',
        chineseName: '精准制导',
        describe: '神经同步锁定技术驱动的高精度制导系统，实时分析目标轨迹进行预判性打击，弹丸具有追踪能力，即使最敏捷的目标也难以逃脱，是Boss的精准打击手段。',
        bulletSpeed: 5.0,
        bulletCount: 1,
        fireRate: 0.05,
        cooldown: 0,
        color: '#ff8844',
        maxLevel: 9,
    },
    [BossWeaponType.SPREAD]: {
        type: BossWeaponType.SPREAD,
        id: 'boss_weapon_spread',
        name: 'Spread',
        chineseName: '扇形散射',
        describe: '多弹头系统母弹发射后分裂为多枚子弹形成扇形攻击面，子弹间产生量子纠缠效应，具有一定的追踪能力，即使部分被拦截其余仍保持高精度打击，是Boss的范围压制手段。',
        bulletSpeed: 4.0,
        bulletCount: 3,
        fireRate: 0.05,
        cooldown: 0,
        color: '#44ff88',
        maxLevel: 9,
    },
    [BossWeaponType.HOMING]: {
        type: BossWeaponType.HOMING,
        id: 'boss_weapon_homing',
        name: 'Homing',
        chineseName: '智能追击',
        describe: '搭载微型AI核心和时空感知模块的智能导弹系统，无视物理障碍进行空间跳跃式追踪，具有强大的穿透能力，一旦锁定便穷追不舍直至命中或被摧毁，是Boss的追踪打击手段。',
        bulletSpeed: 4.0,
        bulletCount: 2,
        fireRate: 0.05,
        cooldown: 0,
        color: '#44ffff',
        maxLevel: 9,
    },
    [BossWeaponType.LASER]: {
        type: BossWeaponType.LASER,
        id: 'boss_weapon_laser',
        name: 'Laser',
        chineseName: '粒子光束',
        describe: '核聚变反应产生的超高温粒子流武器系统，切割任何已知物质，激光束具有量子穿透特性，可绕过常规护盾直接攻击目标核心，是Boss的穿透打击手段。',
        bulletSpeed: 2.0,
        bulletCount: 1,
        fireRate: 0.05,
        cooldown: 0,
        color: '#ff44ff',
        maxLevel: 9,
    },
};
